# Homebrew Formula for cloud-deploy
# This is a template - goreleaser will generate the actual formula automatically

class CloudDeploy < Formula
  desc "Manifest-driven multi-cloud deployment tool for AWS, GCP, Azure, and OCI"
  homepage "https://github.com/jvreagan/cloud-deploy"
  version "0.2.0"  # Update this with each release

  # These will be generated by goreleaser
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/jvreagan/cloud-deploy/releases/download/v0.2.0/cloud-deploy_Darwin_arm64.tar.gz"
    sha256 "REPLACE_WITH_ACTUAL_SHA256"
  elsif OS.mac? && Hardware::CPU.intel?
    url "https://github.com/jvreagan/cloud-deploy/releases/download/v0.2.0/cloud-deploy_Darwin_x86_64.tar.gz"
    sha256 "REPLACE_WITH_ACTUAL_SHA256"
  elsif OS.linux? && Hardware::CPU.arm?
    url "https://github.com/jvreagan/cloud-deploy/releases/download/v0.2.0/cloud-deploy_Linux_arm64.tar.gz"
    sha256 "REPLACE_WITH_ACTUAL_SHA256"
  elsif OS.linux? && Hardware::CPU.intel?
    url "https://github.com/jvreagan/cloud-deploy/releases/download/v0.2.0/cloud-deploy_Linux_x86_64.tar.gz"
    sha256 "REPLACE_WITH_ACTUAL_SHA256"
  end

  license "MIT"

  def install
    bin.install "cloud-deploy"
    bin.install "manifest-ui"

    # Install web UI assets
    prefix.install "web" if Dir.exist?("web")
  end

  test do
    system "#{bin}/cloud-deploy", "-version"
    assert_match "cloud-deploy", shell_output("#{bin}/cloud-deploy -version")
  end
end
